# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0005_auto_20190409_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='managementAddress',
            field=models.CharField(blank=True, help_text=b'Address where this switch can be managed', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='switchport',
            name='kind',
            field=models.CharField(blank=True, choices=[(b'access', b'access'), (b'internet', b'internet')], help_text=b'type of device attached to port', max_length=32, null=True),
        ),
    ]
