# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0007_switch_pipeconf'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='fabric',
            field=models.ForeignKey(blank=True, help_text=b'The Fabric Service which owns this switch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch', to='fabric.FabricService'),
        ),
    ]
