FROM xosproject/xos-synchronizer-base:candidate

ADD . /opt/xos/synchronizers/fabric

ENTRYPOINT []

WORKDIR "/opt/xos/synchronizers/fabric"

CMD bash -c "cd /opt/xos/synchronizers/fabric; ./run-from-api.sh"
